### ISSUE TITLE
Error retrieving hierarchy, no anotations of type 'acoustics'

### ISSUE THREAD

**Issue by MichaelGoodale** [MontrealCorpusTools/polyglot-server#83]
When I tried to use the hierarchy in a page, I get an error. I think this comes from possible changes to the structure of the hierarchy in PolyglotDB and how it's serialised by Django. 
```

ps-app      | Traceback (most recent call last):
ps-app      |   File "/site/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
ps-app      |     response = get_response(request)
ps-app      |   File "/site/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
ps-app      |     response = self.process_exception_by_middleware(e, request)
ps-app      |   File "/site/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
ps-app      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
ps-app      |   File "/site/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
ps-app      |     return view_func(*args, **kwargs)
ps-app      |   File "/site/env/lib/python3.6/site-packages/rest_framework/viewsets.py", line 103, in view
ps-app      |     return self.dispatch(request, *args, **kwargs)
ps-app      |   File "/site/env/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
ps-app      |     response = self.handle_exception(exc)
ps-app      |   File "/site/env/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
ps-app      |     self.raise_uncaught_exception(exc)
ps-app      |   File "/site/env/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
ps-app      |     response = handler(request, *args, **kwargs)
ps-app      |   File "/site/proj/pgdb/api.py", line 342, in hierarchy
ps-app      |     data = serializers.HierarchySerializer(hierarchy).data
ps-app      |   File "/site/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 560, in data
ps-app      |     ret = super(Serializer, self).data
ps-app      |   File "/site/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 262, in data
ps-app      |     self._data = self.to_representation(self.instance)
ps-app      |   File "/site/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 527, in to_representation
ps-app      |     ret[field.field_name] = field.to_representation(attribute)
ps-app      |   File "/site/env/lib/python3.6/site-packages/rest_framework/fields.py", line 1855, in to_representation
ps-app      |     return method(value)
ps-app      |   File "/site/proj/pgdb/serializers.py", line 81, in get_has_pitch_tracks
ps-app      |     return hasattr(obj, 'acoustics') and 'pitch' in obj.acoustics
ps-app      |   File "/site/proj/PolyglotDB/polyglotdb/structure.py", line 62, in __getattr__
ps-app      |     sorted(self.annotation_types)))))
ps-app      | polyglotdb.exceptions.GraphQueryError: The graph does not have any annotations of type 'acoustics'.  Possible types are: phone, word
ps-app      | [27/Jul/2018 19:35:53] ERROR [django.server:124] "GET /api/corpora/1/hierarchy/ HTTP/1.1" 500 16761

```

**Comment by mmcauliffe** [comment]
Ok, pushed a commit that should handle this better than what I thought would handle it.
